import type { Tool } from '@/types'

function favicon(domain: string): string {
  return `https://www.google.com/s2/favicons?domain=${domain}&sz=64`
}

export const DEFAULT_TOOLS: Omit<Tool, '$id' | '$createdAt'>[] = [
  // ─── Languages ─────────────────────────────────────────────────────────────
  { name: 'JavaScript', description: 'The language of the web', categories: ['frontend'], url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript', icon: favicon('developer.mozilla.org'), color: '#f7df1e', tags: ['language', 'web'], userId: 'dev-user', isPublic: true },
  { name: 'TypeScript', description: 'JavaScript with syntax for types', categories: ['frontend'], url: 'https://www.typescriptlang.org', icon: favicon('typescriptlang.org'), color: '#3178c6', tags: ['language', 'types'], userId: 'dev-user', isPublic: true },
  { name: 'Python', description: 'General-purpose programming language', categories: ['backend'], url: 'https://www.python.org', icon: favicon('python.org'), color: '#3776ab', tags: ['language', 'scripting'], userId: 'dev-user', isPublic: true },
  { name: 'Go', description: 'Open source language by Google', categories: ['backend'], url: 'https://go.dev', icon: favicon('go.dev'), color: '#00add8', tags: ['language', 'systems'], userId: 'dev-user', isPublic: true },
  { name: 'Rust', description: 'A language empowering everyone', categories: ['backend'], url: 'https://www.rust-lang.org', icon: favicon('rust-lang.org'), color: '#dea584', tags: ['language', 'systems', 'performance'], userId: 'dev-user', isPublic: true },
  { name: 'Java', description: 'Write once, run anywhere', categories: ['backend'], url: 'https://www.java.com', icon: favicon('java.com'), color: '#f89820', tags: ['language', 'enterprise'], userId: 'dev-user', isPublic: true },
  { name: 'C++', description: 'High-performance systems language', categories: ['backend'], url: 'https://isocpp.org', icon: favicon('isocpp.org'), color: '#00599c', tags: ['language', 'systems'], userId: 'dev-user', isPublic: true },
  { name: 'C#', description: 'Modern object-oriented language by Microsoft', categories: ['backend'], url: 'https://learn.microsoft.com/dotnet/csharp', icon: favicon('learn.microsoft.com'), color: '#68217a', tags: ['language', 'dotnet'], userId: 'dev-user', isPublic: true },
  { name: 'Ruby', description: 'A programmer\'s best friend', categories: ['backend'], url: 'https://www.ruby-lang.org', icon: favicon('ruby-lang.org'), color: '#cc342d', tags: ['language', 'scripting'], userId: 'dev-user', isPublic: true },
  { name: 'PHP', description: 'Server-side scripting language', categories: ['backend'], url: 'https://www.php.net', icon: favicon('php.net'), color: '#777bb4', tags: ['language', 'web'], userId: 'dev-user', isPublic: true },
  { name: 'Swift', description: 'Powerful language for Apple platforms', categories: ['frontend'], url: 'https://swift.org', icon: favicon('swift.org'), color: '#f05138', tags: ['language', 'mobile', 'ios'], userId: 'dev-user', isPublic: true },
  { name: 'Kotlin', description: 'Modern language for JVM and Android', categories: ['backend'], url: 'https://kotlinlang.org', icon: favicon('kotlinlang.org'), color: '#7f52ff', tags: ['language', 'android', 'jvm'], userId: 'dev-user', isPublic: true },
  { name: 'Dart', description: 'Language optimized for client apps', categories: ['frontend'], url: 'https://dart.dev', icon: favicon('dart.dev'), color: '#0175c2', tags: ['language', 'flutter'], userId: 'dev-user', isPublic: true },
  { name: 'Elixir', description: 'Dynamic functional language for scalable apps', categories: ['backend'], url: 'https://elixir-lang.org', icon: favicon('elixir-lang.org'), color: '#6e4a7e', tags: ['language', 'functional', 'erlang'], userId: 'dev-user', isPublic: true },
  { name: 'Zig', description: 'General-purpose language and toolchain', categories: ['backend'], url: 'https://ziglang.org', icon: favicon('ziglang.org'), color: '#f7a41d', tags: ['language', 'systems'], userId: 'dev-user', isPublic: true },

  // ─── Databases ─────────────────────────────────────────────────────────────
  { name: 'PostgreSQL', description: 'Advanced open source relational database', categories: ['database'], url: 'https://www.postgresql.org', icon: favicon('postgresql.org'), color: '#336791', tags: ['sql', 'relational'], userId: 'dev-user', isPublic: true },
  { name: 'MySQL', description: 'World\'s most popular open source database', categories: ['database'], url: 'https://www.mysql.com', icon: favicon('mysql.com'), color: '#4479a1', tags: ['sql', 'relational'], userId: 'dev-user', isPublic: true },
  { name: 'MongoDB', description: 'Document-based distributed database', categories: ['database'], url: 'https://www.mongodb.com', icon: favicon('mongodb.com'), color: '#47a248', tags: ['nosql', 'document'], userId: 'dev-user', isPublic: true },
  { name: 'Redis', description: 'In-memory data structure store', categories: ['database'], url: 'https://redis.io', icon: favicon('redis.io'), color: '#dc382d', tags: ['cache', 'in-memory', 'nosql'], userId: 'dev-user', isPublic: true },
  { name: 'SQLite', description: 'Small, fast, self-contained SQL engine', categories: ['database'], url: 'https://www.sqlite.org', icon: favicon('sqlite.org'), color: '#003b57', tags: ['sql', 'embedded', 'lightweight'], userId: 'dev-user', isPublic: true },
  { name: 'DynamoDB', description: 'Fully managed NoSQL database by AWS', categories: ['database'], url: 'https://aws.amazon.com/dynamodb', icon: favicon('aws.amazon.com'), color: '#4053d6', tags: ['nosql', 'aws', 'serverless'], userId: 'dev-user', isPublic: true },
  { name: 'Supabase', description: 'Open source Firebase alternative', categories: ['database', 'auth', 'backend'], url: 'https://supabase.com', icon: favicon('supabase.com'), color: '#3ecf8e', tags: ['postgres', 'baas', 'realtime', 'storage'], userId: 'dev-user', isPublic: true },
  { name: 'Firebase', description: 'Google\'s mobile and web app platform', categories: ['database', 'auth', 'backend'], url: 'https://firebase.google.com', icon: favicon('firebase.google.com'), color: '#ffca28', tags: ['baas', 'realtime', 'google', 'storage'], userId: 'dev-user', isPublic: true },
  { name: 'Elasticsearch', description: 'Distributed search and analytics engine', categories: ['database'], url: 'https://www.elastic.co/elasticsearch', icon: favicon('elastic.co'), color: '#005571', tags: ['search', 'analytics', 'nosql'], userId: 'dev-user', isPublic: true },
  { name: 'Cassandra', description: 'Distributed wide-column NoSQL database', categories: ['database'], url: 'https://cassandra.apache.org', icon: favicon('cassandra.apache.org'), color: '#1287b1', tags: ['nosql', 'distributed', 'wide-column'], userId: 'dev-user', isPublic: true },
  { name: 'PlanetScale', description: 'Serverless MySQL platform', categories: ['database'], url: 'https://planetscale.com', icon: favicon('planetscale.com'), color: '#000000', tags: ['mysql', 'serverless', 'scaling'], userId: 'dev-user', isPublic: true },
  { name: 'Neon', description: 'Serverless Postgres built for the cloud', categories: ['database'], url: 'https://neon.tech', icon: favicon('neon.tech'), color: '#000000', tags: ['postgres', 'serverless', 'branching'], userId: 'dev-user', isPublic: true },
  { name: 'CockroachDB', description: 'Distributed SQL database', categories: ['database'], url: 'https://www.cockroachlabs.com', icon: favicon('cockroachlabs.com'), color: '#6933ff', tags: ['sql', 'distributed', 'resilient'], userId: 'dev-user', isPublic: true },
  { name: 'Neo4j', description: 'Graph database and analytics platform', categories: ['database'], url: 'https://neo4j.com', icon: favicon('neo4j.com'), color: '#008cc1', tags: ['graph', 'nosql', 'relationships'], userId: 'dev-user', isPublic: true },
  { name: 'InfluxDB', description: 'Time series database', categories: ['database'], url: 'https://www.influxdata.com', icon: favicon('influxdata.com'), color: '#22adf6', tags: ['time-series', 'metrics', 'iot'], userId: 'dev-user', isPublic: true },

  // ─── Frontend Frameworks ───────────────────────────────────────────────────
  { name: 'React', description: 'Library for building user interfaces', categories: ['frontend'], url: 'https://react.dev', icon: favicon('react.dev'), color: '#61dafb', tags: ['framework', 'ui', 'components'], userId: 'dev-user', isPublic: true },
  { name: 'Next.js', description: 'The React framework for the web', categories: ['frontend'], url: 'https://nextjs.org', icon: favicon('nextjs.org'), color: '#ffffff', tags: ['framework', 'ssr', 'react', 'fullstack'], userId: 'dev-user', isPublic: true },
  { name: 'Vue', description: 'Progressive JavaScript framework', categories: ['frontend'], url: 'https://vuejs.org', icon: favicon('vuejs.org'), color: '#42b883', tags: ['framework', 'ui', 'reactive'], userId: 'dev-user', isPublic: true },
  { name: 'Nuxt', description: 'The intuitive Vue framework', categories: ['frontend'], url: 'https://nuxt.com', icon: favicon('nuxt.com'), color: '#00dc82', tags: ['framework', 'ssr', 'vue', 'fullstack'], userId: 'dev-user', isPublic: true },
  { name: 'Svelte', description: 'Cybernetically enhanced web apps', categories: ['frontend'], url: 'https://svelte.dev', icon: favicon('svelte.dev'), color: '#ff3e00', tags: ['framework', 'compiler', 'ui'], userId: 'dev-user', isPublic: true },
  { name: 'SvelteKit', description: 'Web development framework for Svelte', categories: ['frontend'], url: 'https://kit.svelte.dev', icon: favicon('kit.svelte.dev'), color: '#ff3e00', tags: ['framework', 'ssr', 'svelte'], userId: 'dev-user', isPublic: true },
  { name: 'Angular', description: 'Platform for building mobile and desktop web apps', categories: ['frontend'], url: 'https://angular.dev', icon: favicon('angular.dev'), color: '#dd0031', tags: ['framework', 'typescript', 'enterprise'], userId: 'dev-user', isPublic: true },
  { name: 'Astro', description: 'Web framework for content-driven websites', categories: ['frontend'], url: 'https://astro.build', icon: favicon('astro.build'), color: '#bc52ee', tags: ['framework', 'static', 'islands'], userId: 'dev-user', isPublic: true },
  { name: 'Remix', description: 'Full stack web framework', categories: ['frontend'], url: 'https://remix.run', icon: favicon('remix.run'), color: '#121212', tags: ['framework', 'react', 'fullstack'], userId: 'dev-user', isPublic: true },
  { name: 'Solid.js', description: 'Simple and performant reactivity', categories: ['frontend'], url: 'https://www.solidjs.com', icon: favicon('solidjs.com'), color: '#4f88c6', tags: ['framework', 'reactive', 'ui'], userId: 'dev-user', isPublic: true },

  // ─── Frontend Libraries & Tools ────────────────────────────────────────────
  { name: 'Vite', description: 'Next generation frontend tooling', categories: ['frontend'], url: 'https://vitejs.dev', icon: favicon('vitejs.dev'), color: '#646cff', tags: ['bundler', 'build', 'dev-server'], userId: 'dev-user', isPublic: true },
  { name: 'Webpack', description: 'Static module bundler', categories: ['frontend'], url: 'https://webpack.js.org', icon: favicon('webpack.js.org'), color: '#8dd6f9', tags: ['bundler', 'build'], userId: 'dev-user', isPublic: true },
  { name: 'esbuild', description: 'An extremely fast JavaScript bundler', categories: ['frontend'], url: 'https://esbuild.github.io', icon: favicon('esbuild.github.io'), color: '#ffcf00', tags: ['bundler', 'build', 'performance'], userId: 'dev-user', isPublic: true },
  { name: 'Tailwind CSS', description: 'Utility-first CSS framework', categories: ['ui'], url: 'https://tailwindcss.com', icon: favicon('tailwindcss.com'), color: '#06b6d4', tags: ['css', 'utility', 'styling'], userId: 'dev-user', isPublic: true },
  { name: 'shadcn/ui', description: 'Beautifully designed components', categories: ['ui'], url: 'https://ui.shadcn.com', icon: favicon('ui.shadcn.com'), color: '#ffffff', tags: ['components', 'react', 'radix'], userId: 'dev-user', isPublic: true },
  { name: 'Radix UI', description: 'Unstyled, accessible UI primitives', categories: ['ui'], url: 'https://www.radix-ui.com', icon: favicon('radix-ui.com'), color: '#1a1a1a', tags: ['components', 'accessibility', 'primitives'], userId: 'dev-user', isPublic: true },
  { name: 'Framer Motion', description: 'Production-ready motion library for React', categories: ['ui'], url: 'https://www.framer.com/motion', icon: favicon('framer.com'), color: '#0055ff', tags: ['animation', 'react', 'motion'], userId: 'dev-user', isPublic: true },
  { name: 'GSAP', description: 'Professional-grade animation for the web', categories: ['ui'], url: 'https://gsap.com', icon: favicon('gsap.com'), color: '#88ce02', tags: ['animation', 'timeline', 'scroll'], userId: 'dev-user', isPublic: true },
  { name: 'Three.js', description: '3D graphics library for the web', categories: ['ui'], url: 'https://threejs.org', icon: favicon('threejs.org'), color: '#ffffff', tags: ['3d', 'webgl', 'graphics'], userId: 'dev-user', isPublic: true },
  { name: 'D3.js', description: 'Data-driven documents', categories: ['ui'], url: 'https://d3js.org', icon: favicon('d3js.org'), color: '#f9a03c', tags: ['data-viz', 'svg', 'charts'], userId: 'dev-user', isPublic: true },
  { name: 'Zustand', description: 'Small, fast state management', categories: ['frontend'], url: 'https://zustand-demo.pmnd.rs', icon: favicon('pmnd.rs'), color: '#7e43e3', tags: ['state', 'react', 'lightweight'], userId: 'dev-user', isPublic: true },
  { name: 'TanStack Query', description: 'Powerful async state management', categories: ['frontend'], url: 'https://tanstack.com/query', icon: favicon('tanstack.com'), color: '#ff4154', tags: ['data-fetching', 'cache', 'react'], userId: 'dev-user', isPublic: true },
  { name: 'React Hook Form', description: 'Performant forms with easy validation', categories: ['frontend'], url: 'https://react-hook-form.com', icon: favicon('react-hook-form.com'), color: '#ec5990', tags: ['forms', 'validation', 'react'], userId: 'dev-user', isPublic: true },
  { name: 'Zod', description: 'TypeScript-first schema validation', categories: ['frontend'], url: 'https://zod.dev', icon: favicon('zod.dev'), color: '#3e67ec', tags: ['validation', 'schema', 'typescript'], userId: 'dev-user', isPublic: true },

  // ── Backend Frameworks ────────────────────────────────────────────────────
  { name: 'Express', description: 'Fast, minimalist web framework for Node.js', categories: ['backend'], url: 'https://expressjs.com', icon: favicon('expressjs.com'), color: '#ffffff', tags: ['node', 'http', 'minimal'], userId: 'dev-user', isPublic: true },
  { name: 'Fastify', description: 'Fast and low overhead web framework', categories: ['backend'], url: 'https://fastify.dev', icon: favicon('fastify.dev'), color: '#000000', tags: ['node', 'http', 'performance'], userId: 'dev-user', isPublic: true },
  { name: 'NestJS', description: 'Progressive Node.js framework', categories: ['backend'], url: 'https://nestjs.com', icon: favicon('nestjs.com'), color: '#e0234e', tags: ['node', 'typescript', 'enterprise'], userId: 'dev-user', isPublic: true },
  { name: 'Hono', description: 'Ultrafast web framework for the Edges', categories: ['backend'], url: 'https://hono.dev', icon: favicon('hono.dev'), color: '#e36002', tags: ['edge', 'serverless', 'typescript'], userId: 'dev-user', isPublic: true },
  { name: 'Django', description: 'The web framework for perfectionists', categories: ['backend'], url: 'https://www.djangoproject.com', icon: favicon('djangoproject.com'), color: '#092e20', tags: ['python', 'orm', 'batteries-included'], userId: 'dev-user', isPublic: true },
  { name: 'Flask', description: 'Lightweight WSGI web application framework', categories: ['backend'], url: 'https://flask.palletsprojects.com', icon: favicon('palletsprojects.com'), color: '#ffffff', tags: ['python', 'micro', 'simple'], userId: 'dev-user', isPublic: true },
  { name: 'FastAPI', description: 'Modern, fast web framework for Python', categories: ['backend'], url: 'https://fastapi.tiangolo.com', icon: favicon('tiangolo.com'), color: '#009688', tags: ['python', 'async', 'openapi'], userId: 'dev-user', isPublic: true },
  { name: 'Spring Boot', description: 'Java-based framework for building apps', categories: ['backend'], url: 'https://spring.io/projects/spring-boot', icon: favicon('spring.io'), color: '#6db33f', tags: ['java', 'enterprise', 'microservices'], userId: 'dev-user', isPublic: true },
  { name: 'Gin', description: 'HTTP web framework for Go', categories: ['backend'], url: 'https://gin-gonic.com', icon: favicon('gin-gonic.com'), color: '#00add8', tags: ['go', 'http', 'performance'], userId: 'dev-user', isPublic: true },
  { name: 'Actix', description: 'Powerful, pragmatic Rust web framework', categories: ['backend'], url: 'https://actix.rs', icon: favicon('actix.rs'), color: '#000000', tags: ['rust', 'async', 'performance'], userId: 'dev-user', isPublic: true },
  { name: 'Rails', description: 'Web application framework for Ruby', categories: ['backend'], url: 'https://rubyonrails.org', icon: favicon('rubyonrails.org'), color: '#cc0000', tags: ['ruby', 'orm', 'convention'], userId: 'dev-user', isPublic: true },
  { name: 'Laravel', description: 'PHP framework for web artisans', categories: ['backend'], url: 'https://laravel.com', icon: favicon('laravel.com'), color: '#ff2d20', tags: ['php', 'orm', 'elegant'], userId: 'dev-user', isPublic: true },
  { name: 'tRPC', description: 'End-to-end typesafe APIs', categories: ['backend'], url: 'https://trpc.io', icon: favicon('trpc.io'), color: '#398ccb', tags: ['typescript', 'rpc', 'typesafe'], userId: 'dev-user', isPublic: true },

  // ─── DevOps & Infrastructure ───────────────────────────────────────────────
  { name: 'Docker', description: 'Platform for developing and running containers', categories: ['devops'], url: 'https://www.docker.com', icon: favicon('docker.com'), color: '#2496ed', tags: ['containers', 'virtualization'], userId: 'dev-user', isPublic: true },
  { name: 'Kubernetes', description: 'Production-grade container orchestration', categories: ['devops'], url: 'https://kubernetes.io', icon: favicon('kubernetes.io'), color: '#326ce5', tags: ['orchestration', 'containers', 'scaling'], userId: 'dev-user', isPublic: true },
  { name: 'Terraform', description: 'Infrastructure as code', categories: ['devops'], url: 'https://www.terraform.io', icon: favicon('terraform.io'), color: '#7b42bc', tags: ['iac', 'cloud', 'provisioning'], userId: 'dev-user', isPublic: true },
  { name: 'Ansible', description: 'IT automation platform', categories: ['devops'], url: 'https://www.ansible.com', icon: favicon('ansible.com'), color: '#ee0000', tags: ['automation', 'configuration', 'ssh'], userId: 'dev-user', isPublic: true },
  { name: 'GitHub Actions', description: 'Automate your workflow from idea to production', categories: ['devops'], url: 'https://github.com/features/actions', icon: favicon('github.com'), color: '#2088ff', tags: ['ci-cd', 'automation', 'github'], userId: 'dev-user', isPublic: true },
  { name: 'Vercel', description: 'Platform for frontend frameworks and static sites', categories: ['devops'], url: 'https://vercel.com', icon: favicon('vercel.com'), color: '#ffffff', tags: ['hosting', 'serverless', 'edge'], userId: 'dev-user', isPublic: true },
  { name: 'AWS', description: 'Amazon Web Services cloud platform', categories: ['devops'], url: 'https://aws.amazon.com', icon: favicon('aws.amazon.com'), color: '#ff9900', tags: ['cloud', 'iaas', 'paas'], userId: 'dev-user', isPublic: true },
  { name: 'Cloudflare', description: 'Web infrastructure and security company', categories: ['devops'], url: 'https://www.cloudflare.com', icon: favicon('cloudflare.com'), color: '#f38020', tags: ['cdn', 'dns', 'security', 'edge'], userId: 'dev-user', isPublic: true },
  { name: 'Nginx', description: 'High-performance HTTP server and reverse proxy', categories: ['devops'], url: 'https://nginx.org', icon: favicon('nginx.org'), color: '#009639', tags: ['web-server', 'proxy', 'load-balancer'], userId: 'dev-user', isPublic: true },
  { name: 'Linux', description: 'Open source operating system kernel', categories: ['devops'], url: 'https://www.linux.org', icon: favicon('linux.org'), color: '#fcc624', tags: ['os', 'kernel', 'server'], userId: 'dev-user', isPublic: true },

  // ─── Testing ──────────────────────────────────────────────────────────────
  { name: 'Jest', description: 'Delightful JavaScript testing framework', categories: ['testing'], url: 'https://jestjs.io', icon: favicon('jestjs.io'), color: '#c21325', tags: ['unit', 'integration', 'react'], userId: 'dev-user', isPublic: true },
  { name: 'Vitest', description: 'Blazing fast unit test framework', categories: ['testing'], url: 'https://vitest.dev', icon: favicon('vitest.dev'), color: '#6e9f18', tags: ['unit', 'vite', 'typescript'], userId: 'dev-user', isPublic: true },
  { name: 'Cypress', description: 'Fast, easy and reliable testing for anything in a browser', categories: ['testing'], url: 'https://www.cypress.io', icon: favicon('cypress.io'), color: '#17202c', tags: ['e2e', 'browser', 'integration'], userId: 'dev-user', isPublic: true },
  { name: 'Playwright', description: 'Reliable end-to-end testing for modern web apps', categories: ['testing'], url: 'https://playwright.dev', icon: favicon('playwright.dev'), color: '#2eade3', tags: ['e2e', 'cross-browser', 'automation'], userId: 'dev-user', isPublic: true },
  { name: 'Testing Library', description: 'Simple and complete testing utilities', categories: ['testing'], url: 'https://testing-library.com', icon: favicon('testing-library.com'), color: '#e33332', tags: ['unit', 'integration', 'accessibility'], userId: 'dev-user', isPublic: true },

  // ─── Auth ──────────────────────────────────────────────────────────────────
  { name: 'Auth.js', description: 'Authentication for the web (NextAuth)', categories: ['auth'], url: 'https://authjs.dev', icon: favicon('authjs.dev'), color: '#000000', tags: ['oauth', 'nextjs', 'session'], userId: 'dev-user', isPublic: true },
  { name: 'Clerk', description: 'Complete user management platform', categories: ['auth'], url: 'https://clerk.com', icon: favicon('clerk.com'), color: '#6c47ff', tags: ['users', 'auth', 'saas'], userId: 'dev-user', isPublic: true },
  { name: 'Lucia', description: 'Simple and flexible authentication library', categories: ['auth'], url: 'https://lucia-auth.com', icon: favicon('lucia-auth.com'), color: '#e11d48', tags: ['auth', 'session', 'database'], userId: 'dev-user', isPublic: true },
  { name: 'Appwrite', description: 'Open source backend server', categories: ['auth', 'backend', 'database'], url: 'https://appwrite.io', icon: favicon('appwrite.io'), color: '#fd366e', tags: ['baas', 'auth', 'database', 'storage'], userId: 'dev-user', isPublic: true },
  { name: 'Passport.js', description: 'Authentication middleware for Node.js', categories: ['auth'], url: 'https://www.passportjs.org', icon: favicon('passportjs.org'), color: '#34e27a', tags: ['node', 'oauth', 'strategies'], userId: 'dev-user', isPublic: true },

  // ── Monitoring & Observability ────────────────────────────────────────────
  { name: 'Sentry', description: 'Application monitoring and error tracking', categories: ['monitoring'], url: 'https://sentry.io', icon: favicon('sentry.io'), color: '#362d59', tags: ['errors', 'performance', 'tracing'], userId: 'dev-user', isPublic: true },
  { name: 'Datadog', description: 'Monitoring and security platform', categories: ['monitoring'], url: 'https://www.datadoghq.com', icon: favicon('datadoghq.com'), color: '#632ca6', tags: ['metrics', 'logs', 'apm'], userId: 'dev-user', isPublic: true },
  { name: 'Grafana', description: 'Open source analytics and monitoring', categories: ['monitoring'], url: 'https://grafana.com', icon: favicon('grafana.com'), color: '#f46800', tags: ['dashboards', 'metrics', 'visualization'], userId: 'dev-user', isPublic: true },
  { name: 'Prometheus', description: 'Monitoring system and time series database', categories: ['monitoring'], url: 'https://prometheus.io', icon: favicon('prometheus.io'), color: '#e6522c', tags: ['metrics', 'alerting', 'time-series'], userId: 'dev-user', isPublic: true },
  { name: 'New Relic', description: 'Observability platform', categories: ['monitoring'], url: 'https://newrelic.com', icon: favicon('newrelic.com'), color: '#008c99', tags: ['apm', 'logs', 'infrastructure'], userId: 'dev-user', isPublic: true },

  // ─── ORM & Data ────────────────────────────────────────────────────────────
  { name: 'Prisma', description: 'Next-generation ORM for Node.js and TypeScript', categories: ['database'], url: 'https://www.prisma.io', icon: favicon('prisma.io'), color: '#2d3748', tags: ['orm', 'typescript', 'schema'], userId: 'dev-user', isPublic: true },
  { name: 'Drizzle', description: 'TypeScript ORM that feels like SQL', categories: ['database'], url: 'https://orm.drizzle.team', icon: favicon('drizzle.team'), color: '#c5f74f', tags: ['orm', 'typescript', 'sql'], userId: 'dev-user', isPublic: true },
  { name: 'Sequelize', description: 'Promise-based ORM for Node.js', categories: ['database'], url: 'https://sequelize.org', icon: favicon('sequelize.org'), color: '#52b0e7', tags: ['orm', 'node', 'sql'], userId: 'dev-user', isPublic: true },
  { name: 'Mongoose', description: 'MongoDB object modeling for Node.js', categories: ['database'], url: 'https://mongoosejs.com', icon: favicon('mongoosejs.com'), color: '#880000', tags: ['orm', 'mongodb', 'node'], userId: 'dev-user', isPublic: true },

  // ─── API & Communication ───────────────────────────────────────────────────
  { name: 'GraphQL', description: 'Query language for your API', categories: ['backend'], url: 'https://graphql.org', icon: favicon('graphql.org'), color: '#e10098', tags: ['api', 'query', 'schema'], userId: 'dev-user', isPublic: true },
  { name: 'Apollo', description: 'GraphQL implementation for full-stack development', categories: ['backend'], url: 'https://www.apollographql.com', icon: favicon('apollographql.com'), color: '#311c87', tags: ['graphql', 'client', 'server'], userId: 'dev-user', isPublic: true },
  { name: 'Socket.IO', description: 'Real-time bidirectional event-based communication', categories: ['backend'], url: 'https://socket.io', icon: favicon('socket.io'), color: '#010101', tags: ['websocket', 'realtime', 'events'], userId: 'dev-user', isPublic: true },
  { name: 'gRPC', description: 'Modern open source high performance RPC framework', categories: ['backend'], url: 'https://grpc.io', icon: favicon('grpc.io'), color: '#2496ed', tags: ['rpc', 'protobuf', 'microservices'], userId: 'dev-user', isPublic: true },

  // ─── Package Managers & Build ─────────────────────────────────────────────
  { name: 'npm', description: 'Package manager for JavaScript', categories: ['devops'], url: 'https://www.npmjs.com', icon: favicon('npmjs.com'), color: '#cb3837', tags: ['package-manager', 'node', 'registry'], userId: 'dev-user', isPublic: true },
  { name: 'pnpm', description: 'Fast, disk space efficient package manager', categories: ['devops'], url: 'https://pnpm.io', icon: favicon('pnpm.io'), color: '#f9ad00', tags: ['package-manager', 'node', 'performance'], userId: 'dev-user', isPublic: true },
  { name: 'yarn', description: 'Fast, reliable and secure dependency management', categories: ['devops'], url: 'https://yarnpkg.com', icon: favicon('yarnpkg.com'), color: '#2c8ebb', tags: ['package-manager', 'node'], userId: 'dev-user', isPublic: true },
  { name: 'Turborepo', description: 'High-performance build system for monorepos', categories: ['devops'], url: 'https://turborepo.org', icon: favicon('turborepo.org'), color: '#ef4444', tags: ['monorepo', 'build', 'caching'], userId: 'dev-user', isPublic: true },

  // ─── Linting & Formatting ──────────────────────────────────────────────────
  { name: 'ESLint', description: 'Find and fix problems in your JavaScript code', categories: ['testing'], url: 'https://eslint.org', icon: favicon('eslint.org'), color: '#4b32c3', tags: ['linting', 'code-quality', 'javascript'], userId: 'dev-user', isPublic: true },
  { name: 'Prettier', description: 'Opinionated code formatter', categories: ['testing'], url: 'https://prettier.io', icon: favicon('prettier.io'), color: '#f7b93e', tags: ['formatting', 'code-style'], userId: 'dev-user', isPublic: true },
  { name: 'Biome', description: 'Fast formatter and linter for the web', categories: ['testing'], url: 'https://biomejs.dev', icon: favicon('biomejs.dev'), color: '#60a5fa', tags: ['linting', 'formatting', 'performance'], userId: 'dev-user', isPublic: true },

  // ── Version Control ───────────────────────────────────────────────────────
  { name: 'Git', description: 'Distributed version control system', categories: ['devops'], url: 'https://git-scm.com', icon: favicon('git-scm.com'), color: '#f05032', tags: ['vcs', 'version-control', 'collaboration'], userId: 'dev-user', isPublic: true },
  { name: 'GitHub', description: 'Platform for version control and collaboration', categories: ['devops'], url: 'https://github.com', icon: favicon('github.com'), color: '#ffffff', tags: ['vcs', 'hosting', 'collaboration'], userId: 'dev-user', isPublic: true },
  { name: 'GitLab', description: 'Complete DevOps platform', categories: ['devops'], url: 'https://gitlab.com', icon: favicon('gitlab.com'), color: '#fc6d26', tags: ['vcs', 'ci-cd', 'devops'], userId: 'dev-user', isPublic: true },

  // ─── Design & Prototyping ──────────────────────────────────────────────────
  { name: 'Figma', description: 'Collaborative interface design tool', categories: ['ui'], url: 'https://www.figma.com', icon: favicon('figma.com'), color: '#f24e1e', tags: ['design', 'prototyping', 'collaboration'], userId: 'dev-user', isPublic: true },
  { name: 'Storybook', description: 'Frontend workshop for UI development', categories: ['ui'], url: 'https://storybook.js.org', icon: favicon('storybook.js.org'), color: '#ff4785', tags: ['components', 'documentation', 'testing'], userId: 'dev-user', isPublic: true },
]
